// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package raw

import (
	"database/sql"
	"time"
)

type Document struct {
	ID             int64          `json:"id"`
	DocID          string         `json:"docId"`
	Title          string         `json:"title"`
	Description    sql.NullString `json:"description"`
	FileName       string         `json:"fileName"`
	UploadedBy     int64          `json:"uploadedBy"`
	ModifiedAt     time.Time      `json:"modifiedAt"`
	BlockchainHash string         `json:"blockchainHash"`
	UploadedAt     time.Time      `json:"uploadedAt"`
	LastUpdatedAt  time.Time      `json:"lastUpdatedAt"`
}

type User struct {
	ID            int64     `json:"id"`
	UserID        string    `json:"userId"`
	FirstName     string    `json:"firstName"`
	LastName      string    `json:"lastName"`
	IsActive      bool      `json:"isActive"`
	CreatedAt     time.Time `json:"createdAt"`
	LastUpdatedAt time.Time `json:"lastUpdatedAt"`
}
