// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package raw

import (
	"context"
)

type Querier interface {
	AddDoc(ctx context.Context, arg AddDocParams) (Document, error)
	AddUser(ctx context.Context, arg AddUserParams) (User, error)
	GetDoc(ctx context.Context, docID string) (Document, error)
	GetUser(ctx context.Context, userID string) (User, error)
}

var _ Querier = (*Queries)(nil)
